### ISSUE TITLE
Parse json to xmind

### ISSUE THREAD

**Issue by andre-filho** [tobyqin/xmindparser#5]
hey, I was wondering if it is possible to make the other way around, like I have a md or json and parse it to a xmind map. Can this be actually made?

**Comment by tobyqin** [comment]
yes, there is a package named [XMind](https://pypi.org/project/XMind/) can let you create xmind via Python, however, the docs is in Chinese.

It is not very hard to get started, try it then let the author know, he is a good guy.

**Comment by tobyqin** [comment]
for this package, I just did the xmind to json conversion.
