### ISSUE TITLE
能否提供转换pdf, img方式的API?

### ISSUE THREAD

**Issue by yuhaqiang123** [tobyqin/xmindparser#6]

**Comment by tobyqin** [comment]
这些都不是可编程的文件格式，如果需要导出图片，可以直接用xmind，这是手动的方式。

或者调用python zip格式处理的api，xmind可以直接被解压为zip，根目录有一张预览图，通过代码可自动导出。

至于导出pdf，这个就不好具体实现了，可以考虑先导出成markdown然后再转成pdf，但这都不应该是我这个包考虑的情况。
